### ISSUE TITLE
Debug pdf loading in Safari

### ISSUE THREAD

**Issue by arfon** [openjournals/theoj#261] opened 2016-02-11 21:40 UTC
Since the update of webcomponents to `0.7.12` the site now loads in Safari (yay) but the PDF fails to load. See http://astro.theoj.org/review/arxiv:1207.6827v1 as an example.

Unfortunately it fails silently - @marcrohloff @stuartlynn any ideas how to go about debugging this?

**Comment by marcrohloff** [comment] 2016-02-11 22:29
Maybe switch back if the manual height fixed it?

**Comment by arfon** [comment] 2016-02-11 22:34
> Maybe switch back if the manual height fixed it?

Regardless of whether the height is set manually the PDF still doesn't load unfortunately :-\

**Comment by marcrohloff** [comment] 2016-02-11 22:47
But the PDF did load with the previous version of Polymer?

Marc

**Comment by arfon** [comment] 2016-02-11 22:51
No the site didn't load at all in Safari with the previous version (0.5.4) of webcomponents.

**Comment by marcrohloff** [comment] 2016-02-13 22:13
Maybe it would be worth updating PDF JS from 1.0 to 1.3 ?

Marc

**Comment by arfon** [comment] 2016-02-14 05:19
> Maybe it would be worth updating PDF JS from 1.0 to 1.3?

Just did this in https://github.com/openjournals/theoj/commit/7d010bf61c88fef5db3885ab5caac5d287e76ef3 and unfortunately the PDFs still don't show (at all) even though the site renders now pretty well.

**Comment by freelanceastro** [comment] 2016-02-15 08:19
The problem is that the PDF is loading (hence the silent fail), but it's being displayed in an element that's 2px high. This is a CSS problem: CSS sets the height of the stacked-pdf-reader element at 100%, but for some reason Safari doesn't understand this. We can solve this temporarily by eliminating that line of CSS -- doing so reveals the PDF in Safari, and preserves PDF display in Chrome (and presumably in FF and IE). The only catch is that this causes the PDF to look blurry if the window is resized to a much larger size. That, to me, is acceptable right now.

**Comment by freelanceastro** [comment] 2016-02-20 18:45
Our CSS hack doesn't resolve the underlying issue, but we have this working for now, so I'm going to close this issue.

**Closed by freelanceastro** 2016-02-20 18:45 UTC
